### ISSUE TITLE
Are there plans to release the latest and greatest?

### ISSUE THREAD

**Issue by joshuatbrown** [Quintschaf/SwiftyOpenGraph#1]
It looks like there are a couple nice changes since the last official [release](https://github.com/FiveSheepCo/SwiftyOpenGraph/releases) of 1.0.1 on Jan 6, 2022. Are there any plans to put them into a release?

**Comment by JannThomas** [comment]
Hi,

To me it seems like none of these changes change anything in the usable source code of the package or its functionality. I only see test and CI improvements. So as far as I'm concerned I would say no, but correct my statements above if I'm wrong.

**Comment by joshuatbrown** [comment]
Oh, I assumed this one might be necessary but haven't actually tried adding SwiftyOpenGraph as a Swift Package Dependency yet:
https://github.com/FiveSheepCo/SwiftyOpenGraph/commit/4c50b2eb18c95e7e3480add7f39807cfe31d8d31

**Comment by JannThomas** [comment]
I guess it is good to future proof with that one, even though until now a redirect should have fixed the problem. Will release a new version! 😊

**Comment by SplittyDev** [comment]
@joshuatbrown Our org was previously called Quintschaf, and GitHub automatically redirects to the new one, so adding the package should work even with the old URL. I generally agree that we should probably release that change though, just in case
